kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv0002
  namespace: sonar
  labels:
    type: local
spec:
  storageClassName: gp2
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /data/postgresql/

